function DMComputation(DataSetStartIndex, DataSetEndIndex, DistanceIndex)
    % Distance Measures into consideration
    % ED = 1
    % NCCc = 2
    % cDTW with defined window = 3
    Distances = [cellstr('ED'), 'NCCc', 'cDTWX'];
    
    %Datasets 2018
    Datasets2 = [cellstr('ChlorineConcentration'),'ACSF1','Adiac','AllGestureWiimoteX'...
        'AllGestureWiimoteY','AllGestureWiimoteZ', 'ArrowHead','Beef','BeetleFly'...
        'BirdChicken','BME','Car','CBF','Chinatown','ChlorineConcentration','CinCECGTorso'...
        'Coffee','Computers','CricketX','CricketY','CricketZ','Crop','DiatomSizeReduction'...
        'DistalPhalanxOutlineAgeGroup','DistalPhalanxOutlineCorrect','DistalPhalanxTW'...
        'DodgerLoopGame','DodgerLoopWeekend','Earthquakes','ECG200','ECG5000'...
        'ECGFiveDays','ElectricDevices','EOGHorizontalSignal','EOGVerticalSignal','EthanolLevel'...
        'FaceAll','FaceFour','FacesUCR','FiftyWords','Fish','FordA','FordB','FreezerRegularTrain'...
        'FreezerSmallTrain','Fungi','GestureMidAirD1','GestureMidAirD2','GestureMidAirD3','GesturePebbleZ1'...
        'GesturePebbleZ2','GunPoint','GunPointAgeSpan','GunPointMaleVersusFemale','GunPointOldVersusYoung'...
        'Ham','HandOutlines','Haptics','Herring','HouseTwenty','InlineSkate','InsectEPGRegularTrain'...
        'InsectEPGSmallTrain','InsectWingbeatSound','ItalyPowerDemand','LargeKitchenAppliances'...
        'Lightning2','Lightning7','Mallat','Meat','MedicalImages','MelbournePedestrian','MiddlePhalanxOutlineAgeGroup'...
        'MiddlePhalanxOutlineCorrect','MiddlePhalanxTW','MixedShapesRegularTrain','MixedShapesSmallTrain'...
        'MoteStrain','NonInvasiveFetalECGThorax1','NonInvasiveFetalECGThorax2','OliveOil','OSULeaf'...
        'PhalangesOutlinesCorrect','Phoneme','PickupGestureWiimoteZ','PigAirwayPressure','PigArtPressure'...
        'PigCVP','PLAID','Plane','PowerCons','ProximalPhalanxOutlineAgeGroup','ProximalPhalanxOutlineCorrect'...
        'ProximalPhalanxTW','RefrigerationDevices','Rock','ScreenType','SemgHandGenderCh2'...
        'SemgHandMovementCh2', 'SemgHandSubjectCh2','ShakeGestureWiimoteZ','ShapeletSim'...
        'ShapesAll','SmallKitchenAppliances','SmoothSubspace','SonyAIBORobotSurface1'...
        'SonyAIBORobotSurface2','StarLightCurves','Strawberry','SwedishLeaf'...
        'Symbols','SyntheticControl','ToeSegmentation1','ToeSegmentation2','Trace'...
        'TwoLeadECG','TwoPatterns','UMD','UWaveGestureLibraryAll','UWaveGestureLibraryX'...
        'UWaveGestureLibraryY','UWaveGestureLibraryZ','Wafer','Wine','WordSynonyms'...
        'Worms','WormsTwoClass','Yoga'
        ];
    % Datasets 2015 
    Datasets1 = [cellstr('ChlorineConcentration'), 'CinC_ECG_torso',  'DiatomSizeReduction', 'ECGFiveDays', 'FacesUCR', ... 
        'Haptics', 'InlineSkate', 'ItalyPowerDemand', 'MALLAT', 'MedicalImages', 'MoteStrain', 'SonyAIBORobotSurface', ...
        'SonyAIBORobotSurfaceII', 'Symbols', 'TwoLeadECG', 'WordsSynonyms', 'Cricket_X', 'Cricket_Y', 'Cricket_Z',...
        'uWaveGestureLibrary_X', 'uWaveGestureLibrary_Y', 'uWaveGestureLibrary_Z', '50words', 'Adiac', 'Beef',    ...
        'CBF', 'Coffee', 'ECG200', 'FaceAll', 'FaceFour', 'Fish', 'Gun_Point', 'Lighting2', 'Lighting7', 'Plane', ...
        'OliveOil', 'OSULeaf', 'SwedishLeaf', 'Synthetic_control', 'Trace', 'Two_Patterns', 'Wafer', 'Yoga', 'Car'...
        'StarLightCurves', 'InsectWingbeatSound','NonInvasiveFatalECG_Thorax1','NonInvasiveFatalECG_Thorax2'];
     
    %sample
    Datasets = [cellstr('Adiac'),'Beef'];                    
    % Sort Datasets and their corresponding Windows (for cDTW)
    [Datasets, DSOrder] = sort(Datasets);    
    	
    for i = 1:length(Datasets)
        
        if (i>=DataSetStartIndex && i<=DataSetEndIndex)
            
            disp(['Dataset being processed: ', char(Datasets(i))]);

            DS = LoadUCRdataset(char(Datasets(i)));

            % For cDTW
            DS.DTW_WindowPercentage = round(5/100 * length(DS.Data(1,:)));

            DM = [];

            switch DistanceIndex            
                case 1
                    DM = ComputeED_DM(DS.Data);
                case 2
                    DM = ComputeSBD_DM(DS.Data);
                case 3
                    DM = ComputeDTW_DM(DS.Data,DS.DTW_WindowPercentage);
            end

            dlmwrite( strcat( 'DATASETS/',char(Datasets(i)),'/', char(Datasets(i)), '_', char(Distances(DistanceIndex)) ,'.distmatrix'), DM, 'delimiter', '\t');
            
        end
        
    end

end